cpcodes:
  project1:
    - 000000
    - 000000
    - 000000
  project2:
    - 000000
    - 000000
notificationList:
  - user@email.com
  - user@email.com
  - user@email.com
defaultEnvironment: staging
defaultProject: project1
akamaiUser: USER@DOMAIN.COM
akamaiPW: YOURPASSWORD
