cpcodes:
  learn:
    - 000000
    - 000000
    - 000000
  flh:
    - 000000
    - 000000
notificationList:
  - user@email.com
defaultEnvironment: staging
defaultProject: job1
akamaiUser: user@email.com
akamaiPW: password
