cpcodes:
  learn:
    - 226843
    - 226844
    - 226847
  flh:
    - 250086
    - 250087
notificationList:
  - joe.osborne@aquilent.com
defaultEnvironment: staging
defaultProject: learn
akamaiUser: joe.osborne@aquilent.com
akamaiPW: jZsL7FAs2RngXa
